#pragma once

#include "Pfieffer.h"

namespace foxtrot {
    namespace devices {
        enum class TC110_parameter_no : short unisgned
        {
            Heating = 1,
            Standby = 2,
            RUTimeCtrl = 4,
            ErrorAckn = 9,
            PumpgStatn = 10,
            EnableVent = 12,
            CfgSpdSwPt = 17,
            CfgDO2 = 19,
            MotorPump = 23,
            CfgDO1 = 24,
            OpModeBKP = 25,
            SpdSetMode = 26,
            GasMode = 27,
            CfgAccA1 = 35,
            CfgAccB1 = 36,
            CfgAccA2 = 37,
            CfgAccB2 = 38,
            SealingGas = 50,
            CfgAO1 = 55,
            CtrlViaInt = 60,
            IntSelLckd = 61,
            CfgDI1 = 62,
            CfgDI2 = 63,
            RemotePrio = 300,
            SpdSwPtAtt = 302,
            ErrorCode = 303,
            OvTempElec = 304,
            OvTempPump = 305,
            SetSpdAtt = 306,
            PumpAccel = 307,
            SetRotSpdHz = 308,
            ActualSpdHz = 309,
            DrvCurrent = 310,
            OpHrsPump = 311,
            FWVersion = 312,
            DrvVoltage = 313,
            OpHrsElec = 314,
            NominalSpd = 315,
            DrvPower = 316,
            PumpCycles = 319,
            TempElec = 326,
            TempPmpBot = 330,
            AccelDecel = 336,
            TempBearing = 342,
            TempMotor = 346,
            ElecName = 349,
            HWVersion = 354,
            ErrHist1 = 360,
            ErrHist2 = 361,
            ErrHist3 = 362,
            ErrHist4 = 363,
            ErrHist5 = 364,
            ErrHist6 = 365,
            ErrHist7 = 366,
            ErrHist8 = 367,
            ErrHist9 = 368,
            ErrHist10 = 369,
            SetRotSpdRPM = 397,
            ActualSpdRPM = 398,
            NominalSpdRPM = 399,
            RUTimeSVal = 700,
            SpdSwPt1 = 701,
            SpdSVal = 707,
            PwdSVal = 708,
            SwoffBKP = 710,
            SwonBKP = 711,
            StdbySVal = 717,
            SpdSwPt2 = 719,
            VentSpd = 720,
            VentTime = 721,
            NomSpdConf = 777,
            RS485Addr = 797
            
        };
        
    }
}
