# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import foxtrot_pb2 as foxtrot__pb2


class exptserveStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InvokeCapability = channel.unary_unary(
        '/foxtrot.exptserve/InvokeCapability',
        request_serializer=foxtrot__pb2.capability_request.SerializeToString,
        response_deserializer=foxtrot__pb2.capability_response.FromString,
        )
    self.DescribeServer = channel.unary_unary(
        '/foxtrot.exptserve/DescribeServer',
        request_serializer=foxtrot__pb2.empty.SerializeToString,
        response_deserializer=foxtrot__pb2.servdescribe.FromString,
        )
    self.FetchData = channel.unary_stream(
        '/foxtrot.exptserve/FetchData',
        request_serializer=foxtrot__pb2.chunk_request.SerializeToString,
        response_deserializer=foxtrot__pb2.datachunk.FromString,
        )


class exptserveServicer(object):

  def InvokeCapability(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DescribeServer(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchData(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_exptserveServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InvokeCapability': grpc.unary_unary_rpc_method_handler(
          servicer.InvokeCapability,
          request_deserializer=foxtrot__pb2.capability_request.FromString,
          response_serializer=foxtrot__pb2.capability_response.SerializeToString,
      ),
      'DescribeServer': grpc.unary_unary_rpc_method_handler(
          servicer.DescribeServer,
          request_deserializer=foxtrot__pb2.empty.FromString,
          response_serializer=foxtrot__pb2.servdescribe.SerializeToString,
      ),
      'FetchData': grpc.unary_stream_rpc_method_handler(
          servicer.FetchData,
          request_deserializer=foxtrot__pb2.chunk_request.FromString,
          response_serializer=foxtrot__pb2.datachunk.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'foxtrot.exptserve', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
