# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxtrot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ft_error_pb2 as ft__error__pb2
from . import ft_types_pb2 as ft__types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='foxtrot.proto',
  package='foxtrot',
  syntax='proto3',
  serialized_options=b'\n\nio.foxtrot',
  serialized_pb=b'\n\rfoxtrot.proto\x12\x07\x66oxtrot\x1a\x0e\x66t_error.proto\x1a\x0e\x66t_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n\x16\x62roadcast_notification\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\r\n\x05msgid\x18\x02 \x01(\r\x12\x19\n\x11use_default_title\x18\x03 \x01(\x08\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x1b\n\x13use_default_channel\x18\x06 \x01(\x08\x12\x16\n\x0e\x63hannel_target\x18\x07 \x01(\t\"\xd3\x01\n\x0bserver_info\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x16\n\x0eserver_version\x18\x02 \x01(\r\x12\x13\n\x0brpc_version\x18\x03 \x01(\r\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07\x63omment\x18\x05 \x01(\t\x12+\n\x07started\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0coption_flags\x18\x07 \x01(\r\x12\x14\n\x0cunique_runid\x18\x08 \x01(\x0c\x32\x9d\x01\n\texptserve\x12Y\n\x15\x42roadcastNotification\x12\x1f.foxtrot.broadcast_notification\x1a\x1f.foxtrot.broadcast_notification\x12\x35\n\rGetServerInfo\x12\x0e.foxtrot.empty\x1a\x14.foxtrot.server_infoB\x0c\n\nio.foxtrotb\x06proto3'
  ,
  dependencies=[ft__error__pb2.DESCRIPTOR,ft__types__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_BROADCAST_NOTIFICATION = _descriptor.Descriptor(
  name='broadcast_notification',
  full_name='foxtrot.broadcast_notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.broadcast_notification.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.broadcast_notification.msgid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_default_title', full_name='foxtrot.broadcast_notification.use_default_title', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='foxtrot.broadcast_notification.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='foxtrot.broadcast_notification.body', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_default_channel', full_name='foxtrot.broadcast_notification.use_default_channel', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_target', full_name='foxtrot.broadcast_notification.channel_target', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=273,
)


_SERVER_INFO = _descriptor.Descriptor(
  name='server_info',
  full_name='foxtrot.server_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.server_info.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_version', full_name='foxtrot.server_info.server_version', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpc_version', full_name='foxtrot.server_info.rpc_version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='foxtrot.server_info.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='foxtrot.server_info.comment', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='started', full_name='foxtrot.server_info.started', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option_flags', full_name='foxtrot.server_info.option_flags', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unique_runid', full_name='foxtrot.server_info.unique_runid', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=487,
)

_BROADCAST_NOTIFICATION.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SERVER_INFO.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SERVER_INFO.fields_by_name['started'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['broadcast_notification'] = _BROADCAST_NOTIFICATION
DESCRIPTOR.message_types_by_name['server_info'] = _SERVER_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

broadcast_notification = _reflection.GeneratedProtocolMessageType('broadcast_notification', (_message.Message,), {
  'DESCRIPTOR' : _BROADCAST_NOTIFICATION,
  '__module__' : 'foxtrot_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.broadcast_notification)
  })
_sym_db.RegisterMessage(broadcast_notification)

server_info = _reflection.GeneratedProtocolMessageType('server_info', (_message.Message,), {
  'DESCRIPTOR' : _SERVER_INFO,
  '__module__' : 'foxtrot_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.server_info)
  })
_sym_db.RegisterMessage(server_info)


DESCRIPTOR._options = None

_EXPTSERVE = _descriptor.ServiceDescriptor(
  name='exptserve',
  full_name='foxtrot.exptserve',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=490,
  serialized_end=647,
  methods=[
  _descriptor.MethodDescriptor(
    name='BroadcastNotification',
    full_name='foxtrot.exptserve.BroadcastNotification',
    index=0,
    containing_service=None,
    input_type=_BROADCAST_NOTIFICATION,
    output_type=_BROADCAST_NOTIFICATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetServerInfo',
    full_name='foxtrot.exptserve.GetServerInfo',
    index=1,
    containing_service=None,
    input_type=ft__types__pb2._EMPTY,
    output_type=_SERVER_INFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXPTSERVE)

DESCRIPTOR.services_by_name['exptserve'] = _EXPTSERVE

# @@protoc_insertion_point(module_scope)
