# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft_auth.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ft_error_pb2 as ft__error__pb2
from . import ft_types_pb2 as ft__types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft_auth.proto',
  package='foxtrot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rft_auth.proto\x12\x07\x66oxtrot\x1a\x0e\x66t_error.proto\x1a\x0e\x66t_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n\tauth_data\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\x0c\x12\x11\n\tauthlevel\x18\x03 \x01(\x05\x12\x11\n\tauthflags\x18\x04 \x01(\x05\x12*\n\x06\x65xpiry\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1e\n\x0c\x61uth_request\x12\x0e\n\x06userid\x18\x01 \x01(\t\"Y\n\x0e\x61uth_challenge\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x13\n\x0b\x63hallengeid\x18\x02 \x01(\r\x12\x11\n\tchallenge\x18\x03 \x01(\x0c\"A\n\rauth_response\x12\x13\n\x0b\x63hallengeid\x18\x01 \x01(\r\x12\x0e\n\x06userid\x18\x02 \x01(\t\x12\x0b\n\x03sig\x18\x03 \x01(\x0c\"f\n\x0c\x61uth_confirm\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x12\n\nsessionkey\x18\x02 \x01(\x0c\x12\x0e\n\x06\x65xpiry\x18\x03 \x01(\x04\x12\x11\n\tauthlevel\x18\x04 \x01(\x05\"i\n\x0esasl_auth_data\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x11\n\tsasl_data\x18\x02 \x01(\x0c\x12#\n\x07\x61uthdat\x18\x03 \x01(\x0b\x32\x12.foxtrot.auth_data\"I\n\x0e\x61uth_type_list\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x16\n\x0emechanism_name\x18\x02 \x03(\t2\xe6\x02\n\x04\x61uth\x12\x46\n\x14RequestAuthChallenge\x12\x15.foxtrot.auth_request\x1a\x17.foxtrot.auth_challenge\x12\x45\n\x14RespondAuthChallenge\x12\x16.foxtrot.auth_response\x1a\x15.foxtrot.auth_confirm\x12\x45\n\x1aGetSupportedAuthMechanisms\x12\x0e.foxtrot.empty\x1a\x17.foxtrot.auth_type_list\x12G\n\x0fSaslAuthProcess\x12\x17.foxtrot.sasl_auth_data\x1a\x17.foxtrot.sasl_auth_data(\x01\x30\x01\x12?\n\x0bVerifyToken\x12\x17.foxtrot.sasl_auth_data\x1a\x17.foxtrot.sasl_auth_datab\x06proto3'
  ,
  dependencies=[ft__error__pb2.DESCRIPTOR,ft__types__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_AUTH_DATA = _descriptor.Descriptor(
  name='auth_data',
  full_name='foxtrot.auth_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='foxtrot.auth_data.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='foxtrot.auth_data.token', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authlevel', full_name='foxtrot.auth_data.authlevel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authflags', full_name='foxtrot.auth_data.authflags', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='foxtrot.auth_data.expiry', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=215,
)


_AUTH_REQUEST = _descriptor.Descriptor(
  name='auth_request',
  full_name='foxtrot.auth_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='foxtrot.auth_request.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=247,
)


_AUTH_CHALLENGE = _descriptor.Descriptor(
  name='auth_challenge',
  full_name='foxtrot.auth_challenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.auth_challenge.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='challengeid', full_name='foxtrot.auth_challenge.challengeid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='challenge', full_name='foxtrot.auth_challenge.challenge', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=338,
)


_AUTH_RESPONSE = _descriptor.Descriptor(
  name='auth_response',
  full_name='foxtrot.auth_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='challengeid', full_name='foxtrot.auth_response.challengeid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userid', full_name='foxtrot.auth_response.userid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sig', full_name='foxtrot.auth_response.sig', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=405,
)


_AUTH_CONFIRM = _descriptor.Descriptor(
  name='auth_confirm',
  full_name='foxtrot.auth_confirm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.auth_confirm.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionkey', full_name='foxtrot.auth_confirm.sessionkey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='foxtrot.auth_confirm.expiry', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authlevel', full_name='foxtrot.auth_confirm.authlevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=509,
)


_SASL_AUTH_DATA = _descriptor.Descriptor(
  name='sasl_auth_data',
  full_name='foxtrot.sasl_auth_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.sasl_auth_data.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sasl_data', full_name='foxtrot.sasl_auth_data.sasl_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authdat', full_name='foxtrot.sasl_auth_data.authdat', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=616,
)


_AUTH_TYPE_LIST = _descriptor.Descriptor(
  name='auth_type_list',
  full_name='foxtrot.auth_type_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.auth_type_list.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mechanism_name', full_name='foxtrot.auth_type_list.mechanism_name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=691,
)

_AUTH_DATA.fields_by_name['expiry'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_AUTH_CHALLENGE.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_AUTH_CONFIRM.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SASL_AUTH_DATA.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SASL_AUTH_DATA.fields_by_name['authdat'].message_type = _AUTH_DATA
_AUTH_TYPE_LIST.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
DESCRIPTOR.message_types_by_name['auth_data'] = _AUTH_DATA
DESCRIPTOR.message_types_by_name['auth_request'] = _AUTH_REQUEST
DESCRIPTOR.message_types_by_name['auth_challenge'] = _AUTH_CHALLENGE
DESCRIPTOR.message_types_by_name['auth_response'] = _AUTH_RESPONSE
DESCRIPTOR.message_types_by_name['auth_confirm'] = _AUTH_CONFIRM
DESCRIPTOR.message_types_by_name['sasl_auth_data'] = _SASL_AUTH_DATA
DESCRIPTOR.message_types_by_name['auth_type_list'] = _AUTH_TYPE_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

auth_data = _reflection.GeneratedProtocolMessageType('auth_data', (_message.Message,), {
  'DESCRIPTOR' : _AUTH_DATA,
  '__module__' : 'ft_auth_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.auth_data)
  })
_sym_db.RegisterMessage(auth_data)

auth_request = _reflection.GeneratedProtocolMessageType('auth_request', (_message.Message,), {
  'DESCRIPTOR' : _AUTH_REQUEST,
  '__module__' : 'ft_auth_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.auth_request)
  })
_sym_db.RegisterMessage(auth_request)

auth_challenge = _reflection.GeneratedProtocolMessageType('auth_challenge', (_message.Message,), {
  'DESCRIPTOR' : _AUTH_CHALLENGE,
  '__module__' : 'ft_auth_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.auth_challenge)
  })
_sym_db.RegisterMessage(auth_challenge)

auth_response = _reflection.GeneratedProtocolMessageType('auth_response', (_message.Message,), {
  'DESCRIPTOR' : _AUTH_RESPONSE,
  '__module__' : 'ft_auth_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.auth_response)
  })
_sym_db.RegisterMessage(auth_response)

auth_confirm = _reflection.GeneratedProtocolMessageType('auth_confirm', (_message.Message,), {
  'DESCRIPTOR' : _AUTH_CONFIRM,
  '__module__' : 'ft_auth_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.auth_confirm)
  })
_sym_db.RegisterMessage(auth_confirm)

sasl_auth_data = _reflection.GeneratedProtocolMessageType('sasl_auth_data', (_message.Message,), {
  'DESCRIPTOR' : _SASL_AUTH_DATA,
  '__module__' : 'ft_auth_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.sasl_auth_data)
  })
_sym_db.RegisterMessage(sasl_auth_data)

auth_type_list = _reflection.GeneratedProtocolMessageType('auth_type_list', (_message.Message,), {
  'DESCRIPTOR' : _AUTH_TYPE_LIST,
  '__module__' : 'ft_auth_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.auth_type_list)
  })
_sym_db.RegisterMessage(auth_type_list)



_AUTH = _descriptor.ServiceDescriptor(
  name='auth',
  full_name='foxtrot.auth',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=694,
  serialized_end=1052,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestAuthChallenge',
    full_name='foxtrot.auth.RequestAuthChallenge',
    index=0,
    containing_service=None,
    input_type=_AUTH_REQUEST,
    output_type=_AUTH_CHALLENGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RespondAuthChallenge',
    full_name='foxtrot.auth.RespondAuthChallenge',
    index=1,
    containing_service=None,
    input_type=_AUTH_RESPONSE,
    output_type=_AUTH_CONFIRM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSupportedAuthMechanisms',
    full_name='foxtrot.auth.GetSupportedAuthMechanisms',
    index=2,
    containing_service=None,
    input_type=ft__types__pb2._EMPTY,
    output_type=_AUTH_TYPE_LIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaslAuthProcess',
    full_name='foxtrot.auth.SaslAuthProcess',
    index=3,
    containing_service=None,
    input_type=_SASL_AUTH_DATA,
    output_type=_SASL_AUTH_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VerifyToken',
    full_name='foxtrot.auth.VerifyToken',
    index=4,
    containing_service=None,
    input_type=_SASL_AUTH_DATA,
    output_type=_SASL_AUTH_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTH)

DESCRIPTOR.services_by_name['auth'] = _AUTH

# @@protoc_insertion_point(module_scope)
