# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft_capability.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ft_types_pb2 as ft__types__pb2
from . import ft_error_pb2 as ft__error__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft_capability.proto',
  package='foxtrot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x66t_capability.proto\x12\x07\x66oxtrot\x1a\x0e\x66t_types.proto\x1a\x0e\x66t_error.proto\"\x87\x02\n\rdevcapability\x12%\n\x02tp\x18\x01 \x01(\x0e\x32\x19.foxtrot.capability_types\x12\x0f\n\x07\x63\x61pname\x18\x02 \x01(\t\x12\x10\n\x08\x61rgnames\x18\x03 \x03(\t\x12-\n\x08\x61rgtypes\x18\x04 \x03(\x0b\x32\x1b.foxtrot.variant_descriptor\x12,\n\x05rettp\x18\x05 \x01(\x0b\x32\x1b.foxtrot.variant_descriptorH\x00\x12,\n\x08vecrettp\x18\x06 \x01(\x0e\x32\x18.foxtrot.byte_data_typesH\x00\x12\x17\n\rdynamic_rettp\x18\x07 \x01(\x08H\x00\x42\x08\n\x06return\"K\n\x13\x63\x61pability_argument\x12\x10\n\x08position\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.foxtrot.ft_variant\"\x8b\x01\n\x12\x63\x61pability_request\x12\r\n\x05msgid\x18\x01 \x01(\r\x12\r\n\x05\x64\x65vid\x18\x02 \x01(\r\x12\x0f\n\x07\x63\x61pname\x18\x03 \x01(\t\x12*\n\x04\x61rgs\x18\x04 \x03(\x0b\x32\x1c.foxtrot.capability_argument\x12\x1a\n\x12\x63ontention_timeout\x18\x05 \x01(\r\"\x8d\x01\n\x13\x63\x61pability_response\x12\r\n\x05msgid\x18\x01 \x01(\r\x12\r\n\x05\x64\x65vid\x18\x02 \x01(\r\x12\x0f\n\x07\x63\x61pname\x18\x03 \x01(\t\x12&\n\treturnval\x18\x04 \x01(\x0b\x32\x13.foxtrot.ft_variant\x12\x1f\n\x03\x65rr\x18\x05 \x01(\x0b\x32\x12.foxtrot.errstatus*S\n\x10\x63\x61pability_types\x12\x12\n\x0eVALUE_READONLY\x10\x00\x12\x13\n\x0fVALUE_READWRITE\x10\x01\x12\n\n\x06\x41\x43TION\x10\x02\x12\n\n\x06STREAM\x10\x03*\xb1\x01\n\x0f\x62yte_data_types\x12\x0e\n\nUCHAR_TYPE\x10\x00\x12\r\n\tCHAR_TYPE\x10\x01\x12\x0f\n\x0bUSHORT_TYPE\x10\x02\x12\r\n\tUINT_TYPE\x10\x03\x12\x0e\n\nULONG_TYPE\x10\x04\x12\x0e\n\nSHORT_TYPE\x10\x05\x12\r\n\tIINT_TYPE\x10\x06\x12\r\n\tLONG_TYPE\x10\x07\x12\x0f\n\x0b\x42\x46LOAT_TYPE\x10\x08\x12\x10\n\x0c\x42\x44OUBLE_TYPE\x10\tb\x06proto3')
  ,
  dependencies=[ft__types__pb2.DESCRIPTOR,ft__error__pb2.DESCRIPTOR,])

_CAPABILITY_TYPES = _descriptor.EnumDescriptor(
  name='capability_types',
  full_name='foxtrot.capability_types',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALUE_READONLY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_READWRITE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STREAM', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=693,
  serialized_end=776,
)
_sym_db.RegisterEnumDescriptor(_CAPABILITY_TYPES)

capability_types = enum_type_wrapper.EnumTypeWrapper(_CAPABILITY_TYPES)
_BYTE_DATA_TYPES = _descriptor.EnumDescriptor(
  name='byte_data_types',
  full_name='foxtrot.byte_data_types',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UCHAR_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAR_TYPE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USHORT_TYPE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UINT_TYPE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ULONG_TYPE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHORT_TYPE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IINT_TYPE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LONG_TYPE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BFLOAT_TYPE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BDOUBLE_TYPE', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=779,
  serialized_end=956,
)
_sym_db.RegisterEnumDescriptor(_BYTE_DATA_TYPES)

byte_data_types = enum_type_wrapper.EnumTypeWrapper(_BYTE_DATA_TYPES)
VALUE_READONLY = 0
VALUE_READWRITE = 1
ACTION = 2
STREAM = 3
UCHAR_TYPE = 0
CHAR_TYPE = 1
USHORT_TYPE = 2
UINT_TYPE = 3
ULONG_TYPE = 4
SHORT_TYPE = 5
IINT_TYPE = 6
LONG_TYPE = 7
BFLOAT_TYPE = 8
BDOUBLE_TYPE = 9



_DEVCAPABILITY = _descriptor.Descriptor(
  name='devcapability',
  full_name='foxtrot.devcapability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tp', full_name='foxtrot.devcapability.tp', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capname', full_name='foxtrot.devcapability.capname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='argnames', full_name='foxtrot.devcapability.argnames', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='argtypes', full_name='foxtrot.devcapability.argtypes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rettp', full_name='foxtrot.devcapability.rettp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vecrettp', full_name='foxtrot.devcapability.vecrettp', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic_rettp', full_name='foxtrot.devcapability.dynamic_rettp', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='return', full_name='foxtrot.devcapability.return',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=65,
  serialized_end=328,
)


_CAPABILITY_ARGUMENT = _descriptor.Descriptor(
  name='capability_argument',
  full_name='foxtrot.capability_argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='foxtrot.capability_argument.position', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='foxtrot.capability_argument.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=405,
)


_CAPABILITY_REQUEST = _descriptor.Descriptor(
  name='capability_request',
  full_name='foxtrot.capability_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.capability_request.msgid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='devid', full_name='foxtrot.capability_request.devid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capname', full_name='foxtrot.capability_request.capname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='foxtrot.capability_request.args', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contention_timeout', full_name='foxtrot.capability_request.contention_timeout', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=547,
)


_CAPABILITY_RESPONSE = _descriptor.Descriptor(
  name='capability_response',
  full_name='foxtrot.capability_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.capability_response.msgid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='devid', full_name='foxtrot.capability_response.devid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capname', full_name='foxtrot.capability_response.capname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnval', full_name='foxtrot.capability_response.returnval', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.capability_response.err', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=691,
)

_DEVCAPABILITY.fields_by_name['tp'].enum_type = _CAPABILITY_TYPES
_DEVCAPABILITY.fields_by_name['argtypes'].message_type = ft__types__pb2._VARIANT_DESCRIPTOR
_DEVCAPABILITY.fields_by_name['rettp'].message_type = ft__types__pb2._VARIANT_DESCRIPTOR
_DEVCAPABILITY.fields_by_name['vecrettp'].enum_type = _BYTE_DATA_TYPES
_DEVCAPABILITY.oneofs_by_name['return'].fields.append(
  _DEVCAPABILITY.fields_by_name['rettp'])
_DEVCAPABILITY.fields_by_name['rettp'].containing_oneof = _DEVCAPABILITY.oneofs_by_name['return']
_DEVCAPABILITY.oneofs_by_name['return'].fields.append(
  _DEVCAPABILITY.fields_by_name['vecrettp'])
_DEVCAPABILITY.fields_by_name['vecrettp'].containing_oneof = _DEVCAPABILITY.oneofs_by_name['return']
_DEVCAPABILITY.oneofs_by_name['return'].fields.append(
  _DEVCAPABILITY.fields_by_name['dynamic_rettp'])
_DEVCAPABILITY.fields_by_name['dynamic_rettp'].containing_oneof = _DEVCAPABILITY.oneofs_by_name['return']
_CAPABILITY_ARGUMENT.fields_by_name['value'].message_type = ft__types__pb2._FT_VARIANT
_CAPABILITY_REQUEST.fields_by_name['args'].message_type = _CAPABILITY_ARGUMENT
_CAPABILITY_RESPONSE.fields_by_name['returnval'].message_type = ft__types__pb2._FT_VARIANT
_CAPABILITY_RESPONSE.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
DESCRIPTOR.message_types_by_name['devcapability'] = _DEVCAPABILITY
DESCRIPTOR.message_types_by_name['capability_argument'] = _CAPABILITY_ARGUMENT
DESCRIPTOR.message_types_by_name['capability_request'] = _CAPABILITY_REQUEST
DESCRIPTOR.message_types_by_name['capability_response'] = _CAPABILITY_RESPONSE
DESCRIPTOR.enum_types_by_name['capability_types'] = _CAPABILITY_TYPES
DESCRIPTOR.enum_types_by_name['byte_data_types'] = _BYTE_DATA_TYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

devcapability = _reflection.GeneratedProtocolMessageType('devcapability', (_message.Message,), {
  'DESCRIPTOR' : _DEVCAPABILITY,
  '__module__' : 'ft_capability_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.devcapability)
  })
_sym_db.RegisterMessage(devcapability)

capability_argument = _reflection.GeneratedProtocolMessageType('capability_argument', (_message.Message,), {
  'DESCRIPTOR' : _CAPABILITY_ARGUMENT,
  '__module__' : 'ft_capability_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.capability_argument)
  })
_sym_db.RegisterMessage(capability_argument)

capability_request = _reflection.GeneratedProtocolMessageType('capability_request', (_message.Message,), {
  'DESCRIPTOR' : _CAPABILITY_REQUEST,
  '__module__' : 'ft_capability_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.capability_request)
  })
_sym_db.RegisterMessage(capability_request)

capability_response = _reflection.GeneratedProtocolMessageType('capability_response', (_message.Message,), {
  'DESCRIPTOR' : _CAPABILITY_RESPONSE,
  '__module__' : 'ft_capability_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.capability_response)
  })
_sym_db.RegisterMessage(capability_response)


# @@protoc_insertion_point(module_scope)
