# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft_error.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66t_error.proto\"2\n\terrstatus\x12\x18\n\x02tp\x18\x01 \x01(\x0e\x32\x0c.error_types\x12\x0b\n\x03msg\x18\x02 \x01(\t*\xa8\x01\n\x0b\x65rror_types\x12\x0c\n\x08\x66t_Error\x10\x00\x12\x12\n\x0e\x66t_DeviceError\x10\x01\x12\x14\n\x10\x66t_ProtocolError\x10\x02\x12\x10\n\x0cout_of_range\x10\x03\x12\x11\n\runknown_error\x10\x04\x12\x16\n\x12\x63ontention_timeout\x10\x05\x12\x12\n\x0e\x66t_ServerError\x10\x06\x12\x10\n\x0c\x66t_AuthError\x10\x07\x62\x06proto3')
)

_ERROR_TYPES = _descriptor.EnumDescriptor(
  name='error_types',
  full_name='error_types',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ft_Error', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_DeviceError', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_ProtocolError', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='out_of_range', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='unknown_error', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='contention_timeout', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_ServerError', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_AuthError', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=71,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_ERROR_TYPES)

error_types = enum_type_wrapper.EnumTypeWrapper(_ERROR_TYPES)
ft_Error = 0
ft_DeviceError = 1
ft_ProtocolError = 2
out_of_range = 3
unknown_error = 4
contention_timeout = 5
ft_ServerError = 6
ft_AuthError = 7



_ERRSTATUS = _descriptor.Descriptor(
  name='errstatus',
  full_name='errstatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tp', full_name='errstatus.tp', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='errstatus.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=68,
)

_ERRSTATUS.fields_by_name['tp'].enum_type = _ERROR_TYPES
DESCRIPTOR.message_types_by_name['errstatus'] = _ERRSTATUS
DESCRIPTOR.enum_types_by_name['error_types'] = _ERROR_TYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

errstatus = _reflection.GeneratedProtocolMessageType('errstatus', (_message.Message,), {
  'DESCRIPTOR' : _ERRSTATUS,
  '__module__' : 'ft_error_pb2'
  # @@protoc_insertion_point(class_scope:errstatus)
  })
_sym_db.RegisterMessage(errstatus)


# @@protoc_insertion_point(module_scope)
