# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft_flags.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ft_error_pb2 as ft__error__pb2
from . import ft_types_pb2 as ft__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft_flags.proto',
  package='foxtrot',
  syntax='proto3',
  serialized_options=b'\n\nio.foxtrot',
  serialized_pb=b'\n\x0e\x66t_flags.proto\x12\x07\x66oxtrot\x1a\x0e\x66t_error.proto\x1a\x0e\x66t_types.proto\"\xa1\x01\n\nserverflag\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\r\n\x05msgid\x18\x02 \x01(\r\x12\x10\n\x08\x66lagname\x18\x03 \x01(\t\x12\x10\n\x06\x64\x62lval\x18\x04 \x01(\x01H\x00\x12\x10\n\x06intval\x18\x05 \x01(\x11H\x00\x12\x11\n\x07\x62oolval\x18\x06 \x01(\x08H\x00\x12\x13\n\tstringval\x18\x07 \x01(\tH\x00\x42\x05\n\x03\x61rg\"d\n\x0eserverflaglist\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\r\n\x05msgid\x18\x02 \x01(\r\x12\"\n\x05\x66lags\x18\x03 \x03(\x0b\x32\x13.foxtrot.serverflag2\xf5\x01\n\x05\x66lags\x12\x39\n\rSetServerFlag\x12\x13.foxtrot.serverflag\x1a\x13.foxtrot.serverflag\x12\x39\n\rGetServerFlag\x12\x13.foxtrot.serverflag\x1a\x13.foxtrot.serverflag\x12:\n\x0fListServerFlags\x12\x0e.foxtrot.empty\x1a\x17.foxtrot.serverflaglist\x12:\n\x0e\x44ropServerFlag\x12\x13.foxtrot.serverflag\x1a\x13.foxtrot.serverflagB\x0c\n\nio.foxtrotb\x06proto3'
  ,
  dependencies=[ft__error__pb2.DESCRIPTOR,ft__types__pb2.DESCRIPTOR,])




_SERVERFLAG = _descriptor.Descriptor(
  name='serverflag',
  full_name='foxtrot.serverflag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.serverflag.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.serverflag.msgid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flagname', full_name='foxtrot.serverflag.flagname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dblval', full_name='foxtrot.serverflag.dblval', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intval', full_name='foxtrot.serverflag.intval', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boolval', full_name='foxtrot.serverflag.boolval', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stringval', full_name='foxtrot.serverflag.stringval', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='arg', full_name='foxtrot.serverflag.arg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=60,
  serialized_end=221,
)


_SERVERFLAGLIST = _descriptor.Descriptor(
  name='serverflaglist',
  full_name='foxtrot.serverflaglist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.serverflaglist.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.serverflaglist.msgid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='foxtrot.serverflaglist.flags', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=323,
)

_SERVERFLAG.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SERVERFLAG.oneofs_by_name['arg'].fields.append(
  _SERVERFLAG.fields_by_name['dblval'])
_SERVERFLAG.fields_by_name['dblval'].containing_oneof = _SERVERFLAG.oneofs_by_name['arg']
_SERVERFLAG.oneofs_by_name['arg'].fields.append(
  _SERVERFLAG.fields_by_name['intval'])
_SERVERFLAG.fields_by_name['intval'].containing_oneof = _SERVERFLAG.oneofs_by_name['arg']
_SERVERFLAG.oneofs_by_name['arg'].fields.append(
  _SERVERFLAG.fields_by_name['boolval'])
_SERVERFLAG.fields_by_name['boolval'].containing_oneof = _SERVERFLAG.oneofs_by_name['arg']
_SERVERFLAG.oneofs_by_name['arg'].fields.append(
  _SERVERFLAG.fields_by_name['stringval'])
_SERVERFLAG.fields_by_name['stringval'].containing_oneof = _SERVERFLAG.oneofs_by_name['arg']
_SERVERFLAGLIST.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SERVERFLAGLIST.fields_by_name['flags'].message_type = _SERVERFLAG
DESCRIPTOR.message_types_by_name['serverflag'] = _SERVERFLAG
DESCRIPTOR.message_types_by_name['serverflaglist'] = _SERVERFLAGLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

serverflag = _reflection.GeneratedProtocolMessageType('serverflag', (_message.Message,), {
  'DESCRIPTOR' : _SERVERFLAG,
  '__module__' : 'ft_flags_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.serverflag)
  })
_sym_db.RegisterMessage(serverflag)

serverflaglist = _reflection.GeneratedProtocolMessageType('serverflaglist', (_message.Message,), {
  'DESCRIPTOR' : _SERVERFLAGLIST,
  '__module__' : 'ft_flags_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.serverflaglist)
  })
_sym_db.RegisterMessage(serverflaglist)


DESCRIPTOR._options = None

_FLAGS = _descriptor.ServiceDescriptor(
  name='flags',
  full_name='foxtrot.flags',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=326,
  serialized_end=571,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetServerFlag',
    full_name='foxtrot.flags.SetServerFlag',
    index=0,
    containing_service=None,
    input_type=_SERVERFLAG,
    output_type=_SERVERFLAG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetServerFlag',
    full_name='foxtrot.flags.GetServerFlag',
    index=1,
    containing_service=None,
    input_type=_SERVERFLAG,
    output_type=_SERVERFLAG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListServerFlags',
    full_name='foxtrot.flags.ListServerFlags',
    index=2,
    containing_service=None,
    input_type=ft__types__pb2._EMPTY,
    output_type=_SERVERFLAGLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DropServerFlag',
    full_name='foxtrot.flags.DropServerFlag',
    index=3,
    containing_service=None,
    input_type=_SERVERFLAG,
    output_type=_SERVERFLAG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLAGS)

DESCRIPTOR.services_by_name['flags'] = _FLAGS

# @@protoc_insertion_point(module_scope)
