# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft_sessions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ft_error_pb2 as ft__error__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import ft_types_pb2 as ft__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft_sessions.proto',
  package='foxtrot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x66t_sessions.proto\x12\x07\x66oxtrot\x1a\x0e\x66t_error.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0e\x66t_types.proto\"\xb8\x01\n\x0csession_info\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x11\n\tsessionid\x18\x02 \x01(\x0c\x12\x17\n\x0fuser_identifier\x18\x03 \x01(\t\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65vices\x18\x05 \x03(\r\x12\r\n\x05\x66lags\x18\x06 \x03(\t\x12*\n\x06\x65xpiry\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"X\n\x0csession_list\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\'\n\x08sessions\x18\x02 \x03(\x0b\x32\x15.foxtrot.session_info2\xff\x01\n\x08sessions\x12<\n\x0cStartSession\x12\x15.foxtrot.session_info\x1a\x15.foxtrot.session_info\x12<\n\x0c\x43loseSession\x12\x15.foxtrot.session_info\x1a\x15.foxtrot.session_info\x12@\n\x10KeepAliveSession\x12\x15.foxtrot.session_info\x1a\x15.foxtrot.session_info\x12\x35\n\x0cListSessions\x12\x0e.foxtrot.empty\x1a\x15.foxtrot.session_listb\x06proto3'
  ,
  dependencies=[ft__error__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,ft__types__pb2.DESCRIPTOR,])




_SESSION_INFO = _descriptor.Descriptor(
  name='session_info',
  full_name='foxtrot.session_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.session_info.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionid', full_name='foxtrot.session_info.sessionid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_identifier', full_name='foxtrot.session_info.user_identifier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='foxtrot.session_info.comment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='devices', full_name='foxtrot.session_info.devices', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='foxtrot.session_info.flags', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='foxtrot.session_info.expiry', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=280,
)


_SESSION_LIST = _descriptor.Descriptor(
  name='session_list',
  full_name='foxtrot.session_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.session_list.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessions', full_name='foxtrot.session_list.sessions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=370,
)

_SESSION_INFO.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SESSION_INFO.fields_by_name['expiry'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SESSION_LIST.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_SESSION_LIST.fields_by_name['sessions'].message_type = _SESSION_INFO
DESCRIPTOR.message_types_by_name['session_info'] = _SESSION_INFO
DESCRIPTOR.message_types_by_name['session_list'] = _SESSION_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

session_info = _reflection.GeneratedProtocolMessageType('session_info', (_message.Message,), {
  'DESCRIPTOR' : _SESSION_INFO,
  '__module__' : 'ft_sessions_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.session_info)
  })
_sym_db.RegisterMessage(session_info)

session_list = _reflection.GeneratedProtocolMessageType('session_list', (_message.Message,), {
  'DESCRIPTOR' : _SESSION_LIST,
  '__module__' : 'ft_sessions_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.session_list)
  })
_sym_db.RegisterMessage(session_list)



_SESSIONS = _descriptor.ServiceDescriptor(
  name='sessions',
  full_name='foxtrot.sessions',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=373,
  serialized_end=628,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartSession',
    full_name='foxtrot.sessions.StartSession',
    index=0,
    containing_service=None,
    input_type=_SESSION_INFO,
    output_type=_SESSION_INFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseSession',
    full_name='foxtrot.sessions.CloseSession',
    index=1,
    containing_service=None,
    input_type=_SESSION_INFO,
    output_type=_SESSION_INFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='KeepAliveSession',
    full_name='foxtrot.sessions.KeepAliveSession',
    index=2,
    containing_service=None,
    input_type=_SESSION_INFO,
    output_type=_SESSION_INFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListSessions',
    full_name='foxtrot.sessions.ListSessions',
    index=3,
    containing_service=None,
    input_type=ft__types__pb2._EMPTY,
    output_type=_SESSION_LIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONS)

DESCRIPTOR.services_by_name['sessions'] = _SESSIONS

# @@protoc_insertion_point(module_scope)
