# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft_streams.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ft_error_pb2 as ft__error__pb2
from . import ft_capability_pb2 as ft__capability__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft_streams.proto',
  package='foxtrot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x66t_streams.proto\x12\x07\x66oxtrot\x1a\x0e\x66t_error.proto\x1a\x13\x66t_capability.proto\"S\n\x15stream_thread_request\x12\r\n\x05msgid\x18\x01 \x01(\r\x12\x14\n\x0ctick_time_ms\x18\x02 \x01(\r\x12\x15\n\rthreadcomment\x18\x03 \x01(\t\"K\n\x16stream_thread_response\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x10\n\x08threadid\x18\x02 \x01(\r\"\x8f\x01\n\x1bstream_registration_request\x12\r\n\x05msgid\x18\x01 \x01(\r\x12\x10\n\x08threadid\x18\x02 \x01(\r\x12(\n\x03req\x18\x03 \x01(\x0b\x32\x1b.foxtrot.capability_request\x12\x0e\n\x06nticks\x18\x04 \x01(\r\x12\x15\n\rstreamcomment\x18\x05 \x01(\t\"d\n\x1cstream_registration_response\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\r\n\x05msgid\x18\x02 \x01(\r\x12\x14\n\x0cstreamhandle\x18\x03 \x01(\r\"d\n\x0estream_control\x12\r\n\x05msgid\x18\x01 \x01(\r\x12\x14\n\x0cstreamhandle\x18\x02 \x01(\r\x12-\n\x03\x63md\x18\x03 \x01(\x0e\x32 .foxtrot.stream_control_commands\"_\n\nstreamlist\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x30\n\x07threads\x18\x02 \x03(\x0b\x32\x1f.foxtrot.stream_thread_response\"k\n\x10streamthreadlist\x12\x1f\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x12.foxtrot.errstatus\x12\x36\n\x07streams\x18\x02 \x03(\x0b\x32%.foxtrot.stream_registration_response*#\n\x17stream_control_commands\x12\x08\n\x04stop\x10\x00\x62\x06proto3')
  ,
  dependencies=[ft__error__pb2.DESCRIPTOR,ft__capability__pb2.DESCRIPTOR,])

_STREAM_CONTROL_COMMANDS = _descriptor.EnumDescriptor(
  name='stream_control_commands',
  full_name='foxtrot.stream_control_commands',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='stop', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=784,
  serialized_end=819,
)
_sym_db.RegisterEnumDescriptor(_STREAM_CONTROL_COMMANDS)

stream_control_commands = enum_type_wrapper.EnumTypeWrapper(_STREAM_CONTROL_COMMANDS)
stop = 0



_STREAM_THREAD_REQUEST = _descriptor.Descriptor(
  name='stream_thread_request',
  full_name='foxtrot.stream_thread_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.stream_thread_request.msgid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tick_time_ms', full_name='foxtrot.stream_thread_request.tick_time_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threadcomment', full_name='foxtrot.stream_thread_request.threadcomment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=149,
)


_STREAM_THREAD_RESPONSE = _descriptor.Descriptor(
  name='stream_thread_response',
  full_name='foxtrot.stream_thread_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.stream_thread_response.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threadid', full_name='foxtrot.stream_thread_response.threadid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=226,
)


_STREAM_REGISTRATION_REQUEST = _descriptor.Descriptor(
  name='stream_registration_request',
  full_name='foxtrot.stream_registration_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.stream_registration_request.msgid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threadid', full_name='foxtrot.stream_registration_request.threadid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req', full_name='foxtrot.stream_registration_request.req', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nticks', full_name='foxtrot.stream_registration_request.nticks', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='streamcomment', full_name='foxtrot.stream_registration_request.streamcomment', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=372,
)


_STREAM_REGISTRATION_RESPONSE = _descriptor.Descriptor(
  name='stream_registration_response',
  full_name='foxtrot.stream_registration_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.stream_registration_response.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.stream_registration_response.msgid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='streamhandle', full_name='foxtrot.stream_registration_response.streamhandle', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=474,
)


_STREAM_CONTROL = _descriptor.Descriptor(
  name='stream_control',
  full_name='foxtrot.stream_control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='foxtrot.stream_control.msgid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='streamhandle', full_name='foxtrot.stream_control.streamhandle', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='foxtrot.stream_control.cmd', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=576,
)


_STREAMLIST = _descriptor.Descriptor(
  name='streamlist',
  full_name='foxtrot.streamlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.streamlist.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threads', full_name='foxtrot.streamlist.threads', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=673,
)


_STREAMTHREADLIST = _descriptor.Descriptor(
  name='streamthreadlist',
  full_name='foxtrot.streamthreadlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='foxtrot.streamthreadlist.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='streams', full_name='foxtrot.streamthreadlist.streams', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=782,
)

_STREAM_THREAD_RESPONSE.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_STREAM_REGISTRATION_REQUEST.fields_by_name['req'].message_type = ft__capability__pb2._CAPABILITY_REQUEST
_STREAM_REGISTRATION_RESPONSE.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_STREAM_CONTROL.fields_by_name['cmd'].enum_type = _STREAM_CONTROL_COMMANDS
_STREAMLIST.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_STREAMLIST.fields_by_name['threads'].message_type = _STREAM_THREAD_RESPONSE
_STREAMTHREADLIST.fields_by_name['err'].message_type = ft__error__pb2._ERRSTATUS
_STREAMTHREADLIST.fields_by_name['streams'].message_type = _STREAM_REGISTRATION_RESPONSE
DESCRIPTOR.message_types_by_name['stream_thread_request'] = _STREAM_THREAD_REQUEST
DESCRIPTOR.message_types_by_name['stream_thread_response'] = _STREAM_THREAD_RESPONSE
DESCRIPTOR.message_types_by_name['stream_registration_request'] = _STREAM_REGISTRATION_REQUEST
DESCRIPTOR.message_types_by_name['stream_registration_response'] = _STREAM_REGISTRATION_RESPONSE
DESCRIPTOR.message_types_by_name['stream_control'] = _STREAM_CONTROL
DESCRIPTOR.message_types_by_name['streamlist'] = _STREAMLIST
DESCRIPTOR.message_types_by_name['streamthreadlist'] = _STREAMTHREADLIST
DESCRIPTOR.enum_types_by_name['stream_control_commands'] = _STREAM_CONTROL_COMMANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

stream_thread_request = _reflection.GeneratedProtocolMessageType('stream_thread_request', (_message.Message,), {
  'DESCRIPTOR' : _STREAM_THREAD_REQUEST,
  '__module__' : 'ft_streams_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.stream_thread_request)
  })
_sym_db.RegisterMessage(stream_thread_request)

stream_thread_response = _reflection.GeneratedProtocolMessageType('stream_thread_response', (_message.Message,), {
  'DESCRIPTOR' : _STREAM_THREAD_RESPONSE,
  '__module__' : 'ft_streams_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.stream_thread_response)
  })
_sym_db.RegisterMessage(stream_thread_response)

stream_registration_request = _reflection.GeneratedProtocolMessageType('stream_registration_request', (_message.Message,), {
  'DESCRIPTOR' : _STREAM_REGISTRATION_REQUEST,
  '__module__' : 'ft_streams_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.stream_registration_request)
  })
_sym_db.RegisterMessage(stream_registration_request)

stream_registration_response = _reflection.GeneratedProtocolMessageType('stream_registration_response', (_message.Message,), {
  'DESCRIPTOR' : _STREAM_REGISTRATION_RESPONSE,
  '__module__' : 'ft_streams_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.stream_registration_response)
  })
_sym_db.RegisterMessage(stream_registration_response)

stream_control = _reflection.GeneratedProtocolMessageType('stream_control', (_message.Message,), {
  'DESCRIPTOR' : _STREAM_CONTROL,
  '__module__' : 'ft_streams_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.stream_control)
  })
_sym_db.RegisterMessage(stream_control)

streamlist = _reflection.GeneratedProtocolMessageType('streamlist', (_message.Message,), {
  'DESCRIPTOR' : _STREAMLIST,
  '__module__' : 'ft_streams_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.streamlist)
  })
_sym_db.RegisterMessage(streamlist)

streamthreadlist = _reflection.GeneratedProtocolMessageType('streamthreadlist', (_message.Message,), {
  'DESCRIPTOR' : _STREAMTHREADLIST,
  '__module__' : 'ft_streams_pb2'
  # @@protoc_insertion_point(class_scope:foxtrot.streamthreadlist)
  })
_sym_db.RegisterMessage(streamthreadlist)


# @@protoc_insertion_point(module_scope)
