# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft_types.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66t_types.proto\"{\n\nft_variant\x12&\n\tsimplevar\x18\x01 \x01(\x0b\x32\x11.ft_simplevariantH\x00\x12\x1f\n\tstructval\x18\x02 \x01(\x0b\x32\n.ft_structH\x00\x12\x1b\n\x07\x65numval\x18\x03 \x01(\x0b\x32\x08.ft_enumH\x00\x42\x07\n\x05value\"z\n\x10\x66t_simplevariant\x12\x10\n\x06\x64\x62lval\x18\x01 \x01(\x01H\x00\x12\x10\n\x06intval\x18\x02 \x01(\x12H\x00\x12\x11\n\x07uintval\x18\x03 \x01(\x04H\x00\x12\x11\n\x07\x62oolval\x18\x04 \x01(\x08H\x00\x12\x13\n\tstringval\x18\x05 \x01(\tH\x00\x42\x07\n\x05value\"\x81\x01\n\tft_struct\x12\x13\n\x0bstruct_name\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x03(\x0b\x32\x15.ft_struct.ValueEntry\x1a\x39\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.ft_variant:\x02\x38\x01\"\x89\x01\n\x07\x66t_enum\x12\x11\n\tenum_name\x18\x01 \x01(\t\x12\'\n\x08\x65num_map\x18\x02 \x03(\x0b\x32\x15.ft_enum.EnumMapEntry\x12\x12\n\nenum_value\x18\x03 \x01(\r\x1a.\n\x0c\x45numMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')
)




_FT_VARIANT = _descriptor.Descriptor(
  name='ft_variant',
  full_name='ft_variant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simplevar', full_name='ft_variant.simplevar', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='structval', full_name='ft_variant.structval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enumval', full_name='ft_variant.enumval', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='ft_variant.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=18,
  serialized_end=141,
)


_FT_SIMPLEVARIANT = _descriptor.Descriptor(
  name='ft_simplevariant',
  full_name='ft_simplevariant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dblval', full_name='ft_simplevariant.dblval', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intval', full_name='ft_simplevariant.intval', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uintval', full_name='ft_simplevariant.uintval', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boolval', full_name='ft_simplevariant.boolval', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stringval', full_name='ft_simplevariant.stringval', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='ft_simplevariant.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=143,
  serialized_end=265,
)


_FT_STRUCT_VALUEENTRY = _descriptor.Descriptor(
  name='ValueEntry',
  full_name='ft_struct.ValueEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ft_struct.ValueEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ft_struct.ValueEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=397,
)

_FT_STRUCT = _descriptor.Descriptor(
  name='ft_struct',
  full_name='ft_struct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='struct_name', full_name='ft_struct.struct_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ft_struct.value', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FT_STRUCT_VALUEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=397,
)


_FT_ENUM_ENUMMAPENTRY = _descriptor.Descriptor(
  name='EnumMapEntry',
  full_name='ft_enum.EnumMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ft_enum.EnumMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ft_enum.EnumMapEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=537,
)

_FT_ENUM = _descriptor.Descriptor(
  name='ft_enum',
  full_name='ft_enum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enum_name', full_name='ft_enum.enum_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum_map', full_name='ft_enum.enum_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum_value', full_name='ft_enum.enum_value', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FT_ENUM_ENUMMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=537,
)

_FT_VARIANT.fields_by_name['simplevar'].message_type = _FT_SIMPLEVARIANT
_FT_VARIANT.fields_by_name['structval'].message_type = _FT_STRUCT
_FT_VARIANT.fields_by_name['enumval'].message_type = _FT_ENUM
_FT_VARIANT.oneofs_by_name['value'].fields.append(
  _FT_VARIANT.fields_by_name['simplevar'])
_FT_VARIANT.fields_by_name['simplevar'].containing_oneof = _FT_VARIANT.oneofs_by_name['value']
_FT_VARIANT.oneofs_by_name['value'].fields.append(
  _FT_VARIANT.fields_by_name['structval'])
_FT_VARIANT.fields_by_name['structval'].containing_oneof = _FT_VARIANT.oneofs_by_name['value']
_FT_VARIANT.oneofs_by_name['value'].fields.append(
  _FT_VARIANT.fields_by_name['enumval'])
_FT_VARIANT.fields_by_name['enumval'].containing_oneof = _FT_VARIANT.oneofs_by_name['value']
_FT_SIMPLEVARIANT.oneofs_by_name['value'].fields.append(
  _FT_SIMPLEVARIANT.fields_by_name['dblval'])
_FT_SIMPLEVARIANT.fields_by_name['dblval'].containing_oneof = _FT_SIMPLEVARIANT.oneofs_by_name['value']
_FT_SIMPLEVARIANT.oneofs_by_name['value'].fields.append(
  _FT_SIMPLEVARIANT.fields_by_name['intval'])
_FT_SIMPLEVARIANT.fields_by_name['intval'].containing_oneof = _FT_SIMPLEVARIANT.oneofs_by_name['value']
_FT_SIMPLEVARIANT.oneofs_by_name['value'].fields.append(
  _FT_SIMPLEVARIANT.fields_by_name['uintval'])
_FT_SIMPLEVARIANT.fields_by_name['uintval'].containing_oneof = _FT_SIMPLEVARIANT.oneofs_by_name['value']
_FT_SIMPLEVARIANT.oneofs_by_name['value'].fields.append(
  _FT_SIMPLEVARIANT.fields_by_name['boolval'])
_FT_SIMPLEVARIANT.fields_by_name['boolval'].containing_oneof = _FT_SIMPLEVARIANT.oneofs_by_name['value']
_FT_SIMPLEVARIANT.oneofs_by_name['value'].fields.append(
  _FT_SIMPLEVARIANT.fields_by_name['stringval'])
_FT_SIMPLEVARIANT.fields_by_name['stringval'].containing_oneof = _FT_SIMPLEVARIANT.oneofs_by_name['value']
_FT_STRUCT_VALUEENTRY.fields_by_name['value'].message_type = _FT_VARIANT
_FT_STRUCT_VALUEENTRY.containing_type = _FT_STRUCT
_FT_STRUCT.fields_by_name['value'].message_type = _FT_STRUCT_VALUEENTRY
_FT_ENUM_ENUMMAPENTRY.containing_type = _FT_ENUM
_FT_ENUM.fields_by_name['enum_map'].message_type = _FT_ENUM_ENUMMAPENTRY
DESCRIPTOR.message_types_by_name['ft_variant'] = _FT_VARIANT
DESCRIPTOR.message_types_by_name['ft_simplevariant'] = _FT_SIMPLEVARIANT
DESCRIPTOR.message_types_by_name['ft_struct'] = _FT_STRUCT
DESCRIPTOR.message_types_by_name['ft_enum'] = _FT_ENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ft_variant = _reflection.GeneratedProtocolMessageType('ft_variant', (_message.Message,), {
  'DESCRIPTOR' : _FT_VARIANT,
  '__module__' : 'ft_types_pb2'
  # @@protoc_insertion_point(class_scope:ft_variant)
  })
_sym_db.RegisterMessage(ft_variant)

ft_simplevariant = _reflection.GeneratedProtocolMessageType('ft_simplevariant', (_message.Message,), {
  'DESCRIPTOR' : _FT_SIMPLEVARIANT,
  '__module__' : 'ft_types_pb2'
  # @@protoc_insertion_point(class_scope:ft_simplevariant)
  })
_sym_db.RegisterMessage(ft_simplevariant)

ft_struct = _reflection.GeneratedProtocolMessageType('ft_struct', (_message.Message,), {

  'ValueEntry' : _reflection.GeneratedProtocolMessageType('ValueEntry', (_message.Message,), {
    'DESCRIPTOR' : _FT_STRUCT_VALUEENTRY,
    '__module__' : 'ft_types_pb2'
    # @@protoc_insertion_point(class_scope:ft_struct.ValueEntry)
    })
  ,
  'DESCRIPTOR' : _FT_STRUCT,
  '__module__' : 'ft_types_pb2'
  # @@protoc_insertion_point(class_scope:ft_struct)
  })
_sym_db.RegisterMessage(ft_struct)
_sym_db.RegisterMessage(ft_struct.ValueEntry)

ft_enum = _reflection.GeneratedProtocolMessageType('ft_enum', (_message.Message,), {

  'EnumMapEntry' : _reflection.GeneratedProtocolMessageType('EnumMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _FT_ENUM_ENUMMAPENTRY,
    '__module__' : 'ft_types_pb2'
    # @@protoc_insertion_point(class_scope:ft_enum.EnumMapEntry)
    })
  ,
  'DESCRIPTOR' : _FT_ENUM,
  '__module__' : 'ft_types_pb2'
  # @@protoc_insertion_point(class_scope:ft_enum)
  })
_sym_db.RegisterMessage(ft_enum)
_sym_db.RegisterMessage(ft_enum.EnumMapEntry)


_FT_STRUCT_VALUEENTRY._options = None
_FT_ENUM_ENUMMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
